# Generated by Django 5.0.7 on 2024-07-24 12:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
